# Site wide configuration

title:            Roespinosa.co
locale:           en_US
url:              http://roespinosa.co


# Jekyll configuration

<p><img alt="" src="http://postimg.org/image/xkb5dvy95/" /></p>
